version: "3.8"

services:
  frontend:
    image: ghcr.io/ahmed-mahovac/my-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/ahmed-mahovac/my-app-backend:latest
    ports:
      - "8000:80"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USERNAME=${{ secrets.DATABASE_PASSWORD }}
      - DB_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
    depends_on:
      - database
    #command: ["sh", "-c", "php artisan migrate --force && apache2-foreground"] # workaround to keep the container running

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
