version: '3.8'

services:
  frontend:
    image: frontend:latest 
    ports:
      - "3000:3000"
    depends_on:
      - backend 


  backend:
    image: backend:latest
    ports:
      - "8000:80" 
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - database  
    command: ["sh", "-c", "php artisan migrate && php-fpm"] 

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: