version: "3.8"

services:
  frontend:
    image: ghcr.io/ahmed-mahovac/my-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/ahmed-mahovac/my-app-backend:latest
    ports:
      - "8000:80"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USERNAME=$${ DATABASE_USERNAME }
      - DB_PASSWORD=$${ DATABASE_PASSWORD }
      - CACHE_DRIVER=redis
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    command: ["sh", "-c", "php artisan migrate --force && apache2-foreground"] # workaround to keep the container running

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$${ DATABASE_PASSWORD }
      - MYSQL_DATABASE=mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
